### ISSUE TITLE
Research Databricks Integrationtest

### ISSUE THREAD

**Issue by lasrinnil** [Energinet-DataHub/geh-timeseries#372]
### Synopsis
As a PO/SME
I want the developers to investigate possible frameworks for integration tests in DataBricks
so that automated tests are built correctly and so we are building working software that doesn't break when new functionality is deployed.

### Acceptance criteria

- [ ] Investigate how we can test that events published on eventhub is received in a streaming job in DataBricks.
- [ ] Investigate possible frameworks for integration testing in DataBricks
- [ ] Investigate how we can feed integration test with input and output
- [ ] Team is confident in solving a subsequent issue and estimating it: https://github.com/Energinet-DataHub/geh-aggregations/issues/607
- [ ] Decision on which method was chosen must be documented.

### Tech notes

Evaluation criteria for an integration testing strategy / platform:

 - Very easy to run localhost (same tests as in PR gate)
 -  Is part of PR gate
 -  Must support parallel settlement (developers, PR gates, etc.)
 -   Can read from Delta Lake
 -   Can write to Delta Lake
 -   Must give confidence (eg: does it look like "enough" prod?)
 -   DX. eg do not switch between pytest and xunit (?)
 -   perfomance (start-up of container in CI etc)
 -   Should it support performance tests?

### Tasks

- [x] Get reference from Databricks on how to obtain knowledge about integration testing best practices as mentioned in certification course in Databricks Academy. @BjarkeMeier. UPDATE: According to Simon it's probably just referring to knowledge about general koncept for unit and integration testing and not specific to Databricks/Spark.
- [x] Describe scenario ".Net" based on existing tools and strategy. @kristianschneider 
- [x] Describe scenario "nutter". @johevemi 
- [x] Describe scenario "Databricks-connect". @ZavezX
- [x] Describe scenario "Container". @BjarkeMeier and @lasrinnil 
- [x] Evaluate each scenario agains criteria (score or pros/cons or ...?) (all developers)
- [x] Decide on further actions (all developers)

**Comment by MadsBloendAndersen** [comment]
@lasrinnil + @ZavezX jeg har prøvet at skrive noget ned på den her. vil i ikke prøve og kigge det igennem, og tilføje/slette, ellers tager vi den jo også på backlog refinement i morgen. Vil egentlig gerne have dem over i product backloggen.

**Comment by BjarkeMeier** [comment]
# Scenario "Container"

**Assumptions:**
- Unit tests are pytest tests that are executed in container

**Description:**
- Integration tests as pytest tests in container
- Jobs are executed in container on the spark instance (test setup must start the job)
- Non-mockable resources like Event Hub namespace and blob storage for Delta Lakes are available
	- Same concept as TestCommon where resources are provided by Mighty Ducks
	- Connection strings etc are obtained from the keyvault
	- The keyvault url is the sole configuration needed in order to execute the tests
- Regarding CI no changes should be needed as integration tests are just executed by the same action that already execute the unit tests

**Scope:**
- Functionality regarding pyspark (no .NET involved at all)

**Pros:**
- Assuming unit tests run in container and with pytest
	- this will almost just be business as usual regarding coding the tests
	- container dependency will not incur any new overhead
- Good DX by using same tools and strategies for pyspark development
	- not using e.g. .NET
	- same tools, language etc for both unit tests and integration tests

**Cons:**
- Spark instance in container only has a single node(?)
- Is not as close to production environment as we might have liked
- Is not suitable for performance testing

**Comment by kristianschneider** [comment]
# Scenario ":NET"
![image.png](https://images.zenhubusercontent.com/60dae136fad0561c9902148c/00197cae-2477-4ebe-a6fb-b53e6a56d5e9)

**Assumptions:**
- We lean up against the exsisting test.common framework and use .NET code to provission cluster, jobs and deploy and python code into integrationtest resouce group

**Description:**
- The databricks workspace is available in the integration test enviroment, similar to the eventhub and servicebus
- Integration tests are written in .NET using the test.common framework.
- The test will use python code build in either pipeline or VS.code (job.py, package.whl)
- The test will provision the cluster and job for the test run thorugh the databricks API. All functionality is availabel though the Microsoft.Azure.Databricks.Client nuget package
- The test will create storage and eventhub items as allready known in other tests.
- The test copies the required files to databricks via the API in Microsoft.Azure.Databricks.Client
- The test starts the job via the API in Microsoft.Azure.Databricks.Client
- The test sends test data to the eventhub
- The test waits for data in the output storage
- The test EITHER reads directly in the storage or uses another workbook to further analyse and transform the result into a meaningful format fx. json the we can read in .NET. This is usefull for examining very large result dataset
- The test asserts the results, either directly by reading parquet or using the output from a extra resultAnalyser.py job run

**Pros:**
- .NET is familiar to the ART and provides excelent tooling and DX
test.common is a proven approach with support from MightDucks
- We can have a setup that can be closer to production with elements running in Azure and could be scaled similar
- We allready know how to provission parts of the setup with previous timeseries integration test

**Cons:**
- python build is decopled from the rest of the integration test in local dev

**Info:**
https://www.nuget.org/packages/Microsoft.Azure.Databricks.Client/
https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/
https://github.com/Energinet-DataHub/ARCHIVED-green-energy-hub/blob/5fc4fcc28e42a4a030c8704f07ca22afb72b0d96/samples/energinet/integration-test/source/GreenEnergyHub.IntegrationTest/Helpers/ParquetHelper.cs

**Comment by BjarkeMeier** [comment]
This story was overtaken by a team decision on the 28th of February to base the time-series domain on [dotnet spark](https://docs.microsoft.com/en-us/dotnet/spark/) instead of pyspark. That decision naturally leads to the conclusion to build integration tests in .NET and using `TestCommon` and other already existing toolings and used concepts.

_dotnet spark_ has an MIT license. @BjarkeMeier and @ZavezX talked to the software architect who supported the decision. @BjarkeMeier has sent a request to Databricks to possibly get any useful info on the decision. I'll keep the team informed when I get an answer.

I recommend that we close this issue.
